spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/booksmate?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialSize: 10
    min-idle: 5
    maxActive: 20
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 10485760 #10MB
      enabled: true
    #redis  都是默认设置 可以修改
    #Spring Boot 1.0 默认使用的是 Jedis 客户端，2.0 替换成 Lettuce，
    #Lettuce 是一个可伸缩线程安全的 Redis 客户端，多个线程可以共享同一个 RedisConnection
    redis:
      host: 10.10.12.18
      port: 6379
      # Redis数据库索引（默认为0）
      database: 0
      # 连接超时时间（毫秒）
      timeout: 5000
      lettuce:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 8
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
  application:
    name: ms_oauth
server:
  port: 8004
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: 127.0.0.1:${server.port}